// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFSMJhpvFeSugl4HoxnS5X5q2HnuPEsXg',
    appId: '1:559389934036:web:7a8700bbcd5faee073d641',
    messagingSenderId: '559389934036',
    projectId: 'loginpage-ae51c',
    authDomain: 'loginpage-ae51c.firebaseapp.com',
    storageBucket: 'loginpage-ae51c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_6ZDUwn5KEtiIueDrI_7yMtg-zBRknmw',
    appId: '1:559389934036:android:229f99063edac4eb73d641',
    messagingSenderId: '559389934036',
    projectId: 'loginpage-ae51c',
    storageBucket: 'loginpage-ae51c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB1xJXwam8RzamKkegn--n1dodG1JEzDnE',
    appId: '1:559389934036:ios:5dd45cee1afbc3be73d641',
    messagingSenderId: '559389934036',
    projectId: 'loginpage-ae51c',
    storageBucket: 'loginpage-ae51c.appspot.com',
    iosClientId: '559389934036-rsg8dogsf9pdejnk0172trvgh8ssnosg.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB1xJXwam8RzamKkegn--n1dodG1JEzDnE',
    appId: '1:559389934036:ios:5dd45cee1afbc3be73d641',
    messagingSenderId: '559389934036',
    projectId: 'loginpage-ae51c',
    storageBucket: 'loginpage-ae51c.appspot.com',
    iosClientId: '559389934036-rsg8dogsf9pdejnk0172trvgh8ssnosg.apps.googleusercontent.com',
    iosBundleId: 'com.example.app',
  );
}
